name = "rubikvault-site"
compatibility_date = "2025-12-17"

# Cloudflare Pages output folder (must match Pages settings)
pages_build_output_dir = "public"

# KV binding for Pages Functions + local dev
[[kv_namespaces]]
binding = "RV_KV"
id = "323d53e7392e42ff9089daf8977dfde3"
preview_id = "30c57392d8f04dfbaeb71fd8bedea15f"

# Optional: put ONLY non-secret values here (never API keys)
# [vars]
# PROD_URL = "https://rubikvault.com"
# MIRROR_BASE_URL = "https://rubikvault.com"